from socotra_datamart_reports.platform_all_policies_report \
    import AllPoliciesReport
from socotra_datamart_reports.platform_on_risk_report import OnRiskReport
from socotra_datamart_reports.transaction_financial_impact_report \
    import TransactionFinancialImpactReport
